name: Publish Python Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write
  id-token: write  # Crucial para la autorización con PyPI

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Build Package
        run: uv build

      - name: Publish to GitHub Packages
        shell: bash
        run: |
          export UV_PUBLISH_URL=https://pypi.pkg.github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}
          export UV_PUBLISH_USERNAME=${{ github.actor }}
          export UV_PUBLISH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          uv publish

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Al usar Trusted Publishing, no necesitas especificar user ni password aquí
          skip-existing: true
